services:
  dashboard-ui:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production

  bff-java:
    build:
      context: ./bff-java
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "no"]

  risk-service:
    build:
      context: ./mock-risk-service
      dockerfile: Dockerfile
    ports:
      - "9001:9001"
    depends_on:
      - redis

  trading-service:
    build:
      context: ./mock-trading-service
      dockerfile: Dockerfile
    ports:
      - "9002:9002"
    depends_on:
      - redis

  ledger-service:
    build:
      context: ./mock-ledger-service
      dockerfile: Dockerfile
    ports:
      - "9003:9003"
    depends_on:
      - redis

