server:
  port: 8080

spring:
  application:
    name: risk-dashboard-bff
  data:
    redis:
      host: redis
      port: 6379
downstream:
  risk:
    base-url: http://risk-service:9001
  trading:
    base-url: http://trading-service:9002
  ledger:
    base-url: http://ledger-service:9003

management:
  endpoints:
    web:
      exposure:
        include: health,info

